<a href="https://colab.research.google.com/github/one-last-time/FTFL/blob/main/Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Recale Data

Rescaling is useful for optimization algorithms. When the data is comprised of varying scales, many ML algorithms can benefit from rescaling the attributes to all have the same scale. 

In [ ]:
import pandas as pd
import scipy
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [ ]:
url = "https://gist.githubusercontent.com/ktisha/c21e73a1bd1700294ef790c56c8aec1f/raw/819b69b5736821ccee93d05b51de0510bea00294/pima-indians-diabetes.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class'] 
dataframe = pd.read_csv(url, names=names, skiprows=9) 
array = dataframe.values

In [ ]:
dataframe.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

X(SC) = [X-X(MIN)] / [X(MAX) - X(MIN)]

In [ ]:
X = array[:,0:8] 
Y = array[:,8] 
scaler = MinMaxScaler(feature_range=(0, 1)) 
rescaledX = scaler.fit_transform(X) 

In [ ]:
np.set_printoptions(precision=3) 
print(rescaledX[0:5,:]) 

[[0.353 0.744 0.59  0.354 0.    0.501 0.234 0.483]
 [0.059 0.427 0.541 0.293 0.    0.396 0.117 0.167]
 [0.471 0.92  0.525 0.    0.    0.347 0.254 0.183]
 [0.059 0.447 0.541 0.232 0.111 0.419 0.038 0.   ]
 [0.    0.688 0.328 0.354 0.199 0.642 0.944 0.2  ]]


## Binarize Data

- We can transform our data using binary threshold. All values above the threshold are marked 1 and all equal to or below are marked 0

In [ ]:
from sklearn.preprocessing import Binarizer 

In [ ]:
print(X)

[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]


In [ ]:
binarizer = Binarizer(threshold=35).fit(X) 
binaryX = binarizer.transform(X) 
np.set_printoptions(precision=3) 

In [ ]:
print(binaryX[0])

[0. 1. 1. 0. 0. 0. 0. 1.]


# Standardize Data

In [ ]:
from sklearn.preprocessing import StandardScaler 

In [ ]:
scaler = StandardScaler().fit(X) 
rescaledX = scaler.transform(X)

In [ ]:
np.set_printoptions(precision=3) 
print(rescaledX[0:5,:]) 

[[ 0.64   0.848  0.15   0.907 -0.693  0.204  0.468  1.426]
 [-0.845 -1.123 -0.161  0.531 -0.693 -0.684 -0.365 -0.191]
 [ 1.234  1.944 -0.264 -1.288 -0.693 -1.103  0.604 -0.106]
 [-0.845 -0.998 -0.161  0.155  0.123 -0.494 -0.921 -1.042]
 [-1.142  0.504 -1.505  0.907  0.766  1.41   5.485 -0.02 ]]


The values for each attribute now have a mean value of 0 and a standard deviation of 1.